name: App
run-name: ${{ github.sha }}
on:
  push:
    paths:
      - 'src/**'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        type: choice
        options:
          - stg
          - prod

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment || 'stg' }}
    env:
      TARGET_ENV: ${{ inputs.environment || 'stg' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - uses: hashicorp/setup-terraform@v3
      - name: Find Terraform Backend
        run: |
          storageAccountName=$(az storage account list --resource-group rg-bootstrap --query "[?tags.type=='terraform-backend'].name" -o tsv)
          echo "storageAccountName=$storageAccountName" >> $GITHUB_ENV
      - name: Terraform Init
        working-directory: infra/app
        run: terraform init -backend-config="storage_account_name=$storageAccountName" -backend-config="key=app-${{ env.TARGET_ENV }}.tfstate"
      - name: Get Infrastructure Outputs
        run: |
          acrName=$(terraform -chdir=infra/app output -raw acr_name)
          acrLoginServer=$(az acr show --name $acrName --query loginServer -o tsv)
          webAppName=$(terraform -chdir=infra/app output -raw app_service_name)
          appResourceGroup=$(az webapp list --query "[?name=='$webAppName'].resourceGroup" -o tsv)
          echo "acrName=$acrName" >> $GITHUB_ENV
          echo "acrLoginServer=$acrLoginServer" >> $GITHUB_ENV
          echo "webAppName=$webAppName" >> $GITHUB_ENV
          echo "appResourceGroup=$appResourceGroup" >> $GITHUB_ENV
      - name: ACR Login
        run: az acr login --name ${{ env.acrName }}
      - name: Build and push image
        if: github.event_name == 'push' || inputs.environment == 'stg'
        uses: docker/build-push-action@v5
        with:
          context: ./src
          push: true
          tags: |
            ${{ env.acrLoginServer }}/app:latest
            ${{ env.acrLoginServer }}/app:${{ github.sha }}
      - name: Upgrade App Service
        run: az webapp config container set --resource-group $appResourceGroup --name $webAppName --container-image-name $acrLoginServer/app:${{ github.sha }}
